# fly.toml file generated for lineageos-issuebot on 2021-12-11T18:48:50-08:00

app = "lineageos-issuebot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
